apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - sources.yaml
  - releases.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: platform-controllers
      platform.oms/scope: platform-controllers
