apiVersion: v1
kind: ServiceAccount
metadata:
  name: REPLACE_AUTOSCALER_SERVICE_ACCOUNT
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_CLUSTER_AUTOSCALER_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_LOAD_BALANCER_CONTROLLER_ROLE_ARN
