apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/kyverno/charts/kyverno
  ref:
    tag: "3.3.7"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  interval: 30m
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  interval: 30m
  url: https://aws.github.io/eks-charts
