apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongodb

resources:
  - storageclass-gp3-mongodb.yaml
  - certificates.yaml
  - pdb.yaml
  - psmdb-cluster.yaml
  - mongodb-metrics-collector.yaml
  - postgres-metrics-collector.yaml
