apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: psmdb-rs0-pdb
  namespace: mongodb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: percona-server-mongodb
