apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: psmdb
  namespace: mongodb
spec:
  replsets:
    - name: rs0
      serviceAccountName: psmdb-db
      size: 3
      resources:
        requests:
          cpu: "500m"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 2Gi
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: gp3-mongodb
          resources:
            requests:
              storage: 80Gi
  backup:
    enabled: true
    pitr:
      enabled: false
    storages:
      s3-main:
        s3:
          bucket: CHANGE_ME_DEV_BACKUP_BUCKET
          region: CHANGE_ME_AWS_REGION
    tasks:
      - name: daily-full
        enabled: false
